#!/bin/bash

abort ()
{
    MESSAGE=$1

    if ! [ "$MESSAGE" == "" ];
    then
        echo "$MESSAGE"
        echo ""
    fi

    exit 1
}


check_for ()
{
    BIN_PATH=$1
    PACKAGE=$2

    if ! [ -f "$BIN_PATH" ];
    then
        install $PACKAGE
    fi
}


install ()
{
    PACKAGE=$1

    if ! [ "$PACKAGE" == "" ];
    then
        sudo apt install -y $PACKAGE

        if [ "$?" == "1" ];
        then
            echo "-------------------------"
            echo " Package install failed! "
            echo "-------------------------"
            echo ""

            abort
        fi

        return 0
    fi

    abort "Trying to install a unnamed package."
}


