#!/bin/bash

function usage
{
    echo "Usage: floppy_check <drive>"
    echo ""
}


if [ "$1" == "" ];
then
    usage
    exit 1
fi


DRIVE=$1

ufiformat -v -i $DRIVE

if [ "$?" == "1" ];
then
    echo "ERROR: Failed reading floppy."
    echo ""
    exit 1
fi

