#!/bin/bash

file1=$1
file2=$2


if [ "$#" -ne "2" ];
then
    echo "Usage: isnewer <first file/dir> <second file/dir>"
    echo "Returns 0 if first is newer or 1 if second is newer."
    exit -1
fi

if [ "${file1}" -nt "${file2}" ];
then
    echo "First is newer."
    echo ""
    exit 0
else
    echo "Second is newer."
    echo ""
    exit 1
fi

