#!/bin/bash

PYENVS_ROOT=$HOME/.pyenvs

if ! [ "$1" == "" ];
then
    if ! [ -d "${PYENVS_ROOT}/$1" ];
    then
        python -m venv "${PYENVS_ROOT}/$1"

        if [ "$?" == "0" ];
        then
            echo "Created python virtual environment '$1'."
            echo ""
        else
            echo "Failed creating python virtual environment '$1'."
            echo ""
            exit 1
        fi
    fi

    if [ -f "${PYENVS_ROOT}/$1/bin/activate" ];
    then
        echo "You need to execute 'source ${PYENVS_ROOT}/$1/bin/activate' to activate the virtual environment."
        echo "It cannot be called by scripting :(."
        echo ""
        exit 0
    fi
fi
