#!/bin/bash

function abort
{
    if ! [ "$MESSAGE" == "" ];
    then
        echo "$MESSAGE"
        echo ""
    fi

    exit 1
}


UNITY_HUB_REPO="https://hub.unity3d.com/linux/repos/deb"
UNITY_GPG_URL="https://hub.unity3d.com/linux/keys/public"

UNITY_HUB_LIST="/etc/apt/sources.list.d/unityhub.list"
UNITY_HUB_LIST_TMP="/var/tmp/unityhub.list"
UNITY_GPG_KEY="/usr/share/keyrings/Unity_Technologies_ApS.gpg"
UNITY_GPG_TMP="/var/tmp/Unity_Technologies_ApS.gpg"


if [ -f "/usr/local/bin/unityhub" ];
then
    abort "It seems that Unity Hub is already installed..."
fi


if ! [ -f "$UNITY_GPG_KEY" ] || 
   ! [ -f "$UNITY_HUB_LIST" ];
then
    sudo rm "$UNITY_GPG_KEY"
    sudo rm "$UNITY_HUB_LIST"
    
    echo "Preparing APT ..."
    echo "-----------------"

    wget $UNITY_GPG_URL -O $UNITY_GPG_TMP
    
    if [ "$?" == "1" ];
    then
        abort "Failed to download Unity Technologies GPG key."
    fi

    gpg --dearmor $UNITY_GPG_TMP
    sudo mv $UNITY_GPG_TMP $UNITY_GPG_KEY
    
    if [ "$?" == "1" ];
    then
        abort "Failed to install Unity Technologies GPG key."
    fi
    
    UNITY_HUB_LIST_ENTRY="deb [signed-by=$UNITY_GPG_KEY] "
    UNITY_HUB_LIST_ENTRY+="$UNITY_HUB_REPO stable main"
    
    echo "$UNITY_HUB_LIST_ENTRY" > $UNITY_HUB_LIST_TMP
    sudo mv $UNITY_HUB_LIST_TMP $UNITY_HUB_LIST

    if [ "$?" == "1" ];
    then
        abort "Failed!"
    fi

    echo "Done."
    echo ""
fi


echo "Refreshing APT database and installing Unity Hub..."
echo "---------------------------------------------------"

sudo apt update
sudo apt install -y unityhub

echo ""

if [ "$?" == "1" ];
then
    abort "UnityHub installation failed!"
fi


echo "Unity Hub should be installed now."
echo ""
echo "First of all, you will have to create a Unity account and/or login it."
echo -n "Next, you can need to activate your license "
echo "(if it is a Personal one it will be free)."
echo "Then you will be able to install and run your favourite Unity version."
echo ""
echo "Happy programming!"
echo ""
