#!/bin/bash

function abort
{
    if ! [ "$MESSAGE" == "" ];
    then
        echo "$MESSAGE"
        echo ""
    fi

    exit 1
}


UNITY_HUB_REPO="https://hub.unity3d.com/linux/repos/deb"
UNITY_GPG_URL="https://hub.unity3d.com/linux/keys/public"

UNITY_HUB_LIST="/etc/apt/sources.list.d/unityhub.list"
UNITY_HUB_LIST_TMP="/var/tmp/unityhub.list"
UNITY_GPG_KEY="/usr/share/keyrings/Unity_Technologies_ApS.gpg"
UNITY_GPG_TMP="/var/tmp/Unity_Technologies_ApS.gpg"


if [ -f "/usr/bin/unityhub" ];
then
    abort "It seems that Unity Hub is already installed..."
fi


if ! [ -f "$UNITY_GPG_KEY" ] || 
   ! [ -f "$UNITY_HUB_LIST" ];
then
    rm "$UNITY_GPG_TMP" &> /dev/null
    sudo rm "$UNITY_GPG_KEY" &> /dev/null
    sudo rm "$UNITY_HUB_LIST" &> /dev/null
    
    echo "Preparing APT ..."
    echo "-----------------"

    wget $UNITY_GPG_URL -O $UNITY_GPG_TMP
    
    if [ "$?" == "1" ];
    then
        abort "Failed to download Unity Technologies GPG key."
    fi

    gpg --dearmor $UNITY_GPG_TMP
    sudo mv ${UNITY_GPG_TMP}.gpg $UNITY_GPG_KEY
    
    if [ "$?" == "1" ];
    then
        abort "Failed to install Unity Technologies GPG key."
    fi
    
    UNITY_HUB_LIST_ENTRY="deb [signed-by=$UNITY_GPG_KEY] "
    UNITY_HUB_LIST_ENTRY+="$UNITY_HUB_REPO stable main"
    
    echo "$UNITY_HUB_LIST_ENTRY" > $UNITY_HUB_LIST_TMP
    sudo mv $UNITY_HUB_LIST_TMP $UNITY_HUB_LIST

    if [ "$?" == "1" ];
    then
        abort "Failed!"
    fi

    echo "Done."
    echo ""
fi


echo "Refreshing APT database and installing Unity Hub..."
echo "---------------------------------------------------"

sudo apt update
sudo apt install -y unityhub

echo ""

if [ "$?" == "1" ];
then
    abort "UnityHub installation failed!"
fi

if ! [ -d "$HOME/.dotnet" ];
then
    echo "Dotnet will be installed now because it may be needed."
    echo ""

    wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh

    if [ "$?" == "1" ];
    then
        echo "Failed. It is recommended to install later."
        echo "Flease, run 'download_dotnet-installer' manually."

        echo "#!/bin/bash" > download_dotnet-installer
        echo "wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh" >> download_dotnet-installer
        chmod +x download_dotnet-installer
    else
        chmod +x dotnet-install.sh
        ./dotnet-install.sh

        if [ "$?" == "1" ];
        then
            echo "Failed. Run the 'dotnet-install.sh' script again."
            echo ""
        else
            if [ -f "$HOME/.environment" ];
            then
                echo "export PATH=\$HOME/.dotnet:\$PATH" >> "$HOME/.environment"
                echo "Added the .dotnet folder to the PATH via \$HOME/.environment"
            else
                echo "export PATH=\$HOME/.dotnet:\$PATH" >> "$HOME/.bashrc"
                echo "Added the .dotnet folder to the PATH via \$HOME/.bashrc"
            fi
        fi
    fi
fi


echo "Unity Hub should be installed now."
echo ""
echo "You will have to create a Unity account and/or login with it."
echo -n "Next, you may need to activate your license "
echo "(if it is a Personal one it will be free)."
echo "Then you will be able to install and run your favourite Unity version."
echo ""
echo "Happy programming!"
echo ""
